### ISSUE TITLE
TypeError: Cannot read property 'step' of undefined

### ISSUE THREAD

**Issue by boxhead201** [basti1302/traverson#52] opened 2016-01-20 09:14 UTC
Running the plain vanilla example with Node.js on the command line results in "TypeError: Cannot read property 'step' of undefined"  My webserver is not logging a request/response when I run this example.  What could I be doing wrong?

C:\Users\prowe030215\test16>node traverson.js

C:\Users\prowe030215\test16\node_modules\traverson\lib\transforms\fetch_resource.js:45
        log.debug('error while processing step ', t.step);
                                                   ^

TypeError: Cannot read property 'step' of undefined
    at C:\Users\prowe030215\test16\node_modules\traverson\lib\transforms\fetch_resource.js:45:52
    at detectContentType (C:\Users\prowe030215\test16\node_modules\traverson\lib\transforms\detect_content_type.js:16:7)
    at Request._callback (C:\Users\prowe030215\test16\node_modules\traverson\lib\http_requests.js:60:10)
    at Request.self.callback (C:\Users\prowe030215\test16\node_modules\request\request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\prowe030215\test16\node_modules\request\request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\prowe030215\test16\node_modules\request\request.js:962:12)

**Comment by boxhead201** [comment] 2016-01-20 09:32
http_proxy caused the error - making requests go outside instead of my request going to local webserver.

It would be nice to make the error message a bit more meaningful.

**Comment by boxhead201** [comment] 2016-01-20 09:34
Re-opened, another cryptic error.  Is it because I am using HAL ?

C:\Users\prowe030215\test16>node traverson.js
ENTRY
traverson=[object Object]
REQUEST { uri: 'http://localhost:6060/allocation',
  callback: [Function],
  method: 'GET' }
EXIT
REQUEST make request http://localhost:6060/allocation
REQUEST onRequestResponse http://localhost:6060/allocation 200 { server: 'Apache-Coyote/1.1',
  'content-type': 'application/hal+json;charset=UTF-8',
  'transfer-encoding': 'chunked',
  date: 'Wed, 20 Jan 2016 09:33:16 GMT',
  connection: 'close' }
REQUEST reading response's body
REQUEST finish init function http://localhost:6060/allocation
REQUEST response end http://localhost:6060/allocation 200 { server: 'Apache-Coyote/1.1',
  'content-type': 'application/hal+json;charset=UTF-8',
  'transfer-encoding': 'chunked',
  date: 'Wed, 20 Jan 2016 09:33:16 GMT',
  connection: 'close' }
REQUEST end event http://localhost:6060/allocation
REQUEST has body http://localhost:6060/allocation 2219
REQUEST emitting complete http://localhost:6060/allocation
C:\Users\prowe030215\test16\node_modules\traverson\lib\transforms\fetch_resource.js:45
        log.debug('error while processing step ', t.step);
                                                   ^

TypeError: Cannot read property 'step' of undefined
    at C:\Users\prowe030215\test16\node_modules\traverson\lib\transforms\fetch_resource.js:45:52
    at detectContentType (C:\Users\prowe030215\test16\node_modules\traverson\lib\transforms\detect_content_type.js:16:7)
    at Request._callback (C:\Users\prowe030215\test16\node_modules\traverson\lib\http_requests.js:60:10)
    at Request.self.callback (C:\Users\prowe030215\test16\node_modules\request\request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\prowe030215\test16\node_modules\request\request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\prowe030215\test16\node_modules\request\request.js:962:12)

**Comment by basti1302** [comment] 2016-01-22 12:44
Could you please post the exact code that causes this problem? That would make it easier for me to reproduce it. The line number/file name indicates that the traversal has been aborted - do you abort requests via traversal.abort() (see https://github.com/basti1302/traverson/blob/master/user-guide.markdown#aborting-the-link-traversal)?

**Comment by basti1302** [comment] 2016-01-22 13:21
Also, I noticed a problem in traverson that would actually explain the cryptic error message you got - a follow up. I fixed it in version 3.1.2 which I just released. Please try again with this release. It might not solve your problem completely, but at least the actual error message should no longer be shadowed by the `TypeError` you see now and that might help me to investigate further.

Thanks for the report, by the way.

**Comment by basti1302** [comment] 2016-02-01 16:56
Closing because of missing feedback from the OP. Feel free to reopen when ready to provide the information asked for above.

**Closed by basti1302** 2016-02-01 16:56 UTC
